package main

import (
	"ThroneCore/gen"
	"context"
	"sync"

	"google.golang.org/protobuf/proto"
)

// protoRPCServer keeps the current context-based Core implementation intact while
// exposing the net/rpc method signatures generated by protoc-gen-protorpc.
type protoRPCServer struct {
	probeSuccess chan struct{}
	probeOnce    sync.Once
}

var globalServer = new(server)

func adaptProtoRPC[T interface {
	proto.Message
	comparable
}](out T, call func() (T, error)) error {
	response, err := call()
	var zero T
	if response != zero {
		proto.Reset(out)
		proto.Merge(out, response)
	}
	return err
}

func (s *protoRPCServer) Start(in *gen.LoadConfigReq, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) { return globalServer.Start(context.Background(), in) })
}

func (s *protoRPCServer) Stop(in *gen.EmptyReq, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) { return globalServer.Stop(context.Background(), in) })
}

func (s *protoRPCServer) CheckConfig(in *gen.LoadConfigReq, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) { return globalServer.CheckConfig(context.Background(), in) })
}

func (s *protoRPCServer) Test(in *gen.TestReq, out *gen.TestResp) error {
	return adaptProtoRPC(out, func() (*gen.TestResp, error) { return globalServer.Test(context.Background(), in) })
}

func (s *protoRPCServer) StopTest(in *gen.EmptyReq, out *gen.EmptyResp) error {
	return adaptProtoRPC(out, func() (*gen.EmptyResp, error) { return globalServer.StopTest(context.Background(), in) })
}

func (s *protoRPCServer) QueryURLTest(in *gen.EmptyReq, out *gen.QueryURLTestResponse) error {
	return adaptProtoRPC(out, func() (*gen.QueryURLTestResponse, error) { return globalServer.QueryURLTest(context.Background(), in) })
}

func (s *protoRPCServer) QueryStats(in *gen.EmptyReq, out *gen.QueryStatsResp) error {
	return adaptProtoRPC(out, func() (*gen.QueryStatsResp, error) { return globalServer.QueryStats(context.Background(), in) })
}

func (s *protoRPCServer) QueryConnections(in *gen.EmptyReq, out *gen.QueryConnectionsResp) error {
	return adaptProtoRPC(out, func() (*gen.QueryConnectionsResp, error) {
		return globalServer.QueryConnections(context.Background(), in)
	})
}

func (s *protoRPCServer) CloseConnections(in *gen.CloseConnectionsRequest, out *gen.CloseConnectionsResponse) error {
	return adaptProtoRPC(out, func() (*gen.CloseConnectionsResponse, error) {
		return globalServer.CloseConnections(context.Background(), in)
	})
}

func (s *protoRPCServer) SetSystemDNS(in *gen.SetSystemDNSRequest, out *gen.EmptyResp) error {
	return setSystemDNSProtoRPC(in, out)
}

func (s *protoRPCServer) IsPrivileged(in *gen.EmptyReq, out *gen.IsPrivilegedResponse) error {
	err := adaptProtoRPC(out, func() (*gen.IsPrivilegedResponse, error) {
		return globalServer.IsPrivileged(context.Background(), in)
	})
	if err == nil && s.probeSuccess != nil {
		s.probeOnce.Do(func() { close(s.probeSuccess) })
	}
	return err
}

func (s *protoRPCServer) GetDefaultInterface(in *gen.EmptyReq, out *gen.GetDefaultInterfaceResponse) error {
	return adaptProtoRPC(out, func() (*gen.GetDefaultInterfaceResponse, error) {
		return globalServer.GetDefaultInterface(context.Background(), in)
	})
}

func (s *protoRPCServer) SpeedTest(in *gen.SpeedTestRequest, out *gen.SpeedTestResponse) error {
	return adaptProtoRPC(out, func() (*gen.SpeedTestResponse, error) { return globalServer.SpeedTest(context.Background(), in) })
}

func (s *protoRPCServer) QuerySpeedTest(in *gen.EmptyReq, out *gen.QuerySpeedTestResponse) error {
	return adaptProtoRPC(out, func() (*gen.QuerySpeedTestResponse, error) {
		return globalServer.QuerySpeedTest(context.Background(), in)
	})
}

func (s *protoRPCServer) QueryCountryTest(in *gen.EmptyReq, out *gen.QueryCountryTestResponse) error {
	return adaptProtoRPC(out, func() (*gen.QueryCountryTestResponse, error) {
		return globalServer.QueryCountryTest(context.Background(), in)
	})
}

func (s *protoRPCServer) IPTest(in *gen.IPTestRequest, out *gen.IPTestResp) error {
	return adaptProtoRPC(out, func() (*gen.IPTestResp, error) { return globalServer.IPTest(context.Background(), in) })
}

func (s *protoRPCServer) QueryIPTest(in *gen.EmptyReq, out *gen.QueryIPTestResponse) error {
	return adaptProtoRPC(out, func() (*gen.QueryIPTestResponse, error) { return globalServer.QueryIPTest(context.Background(), in) })
}

func (s *protoRPCServer) GenWgKeyPair(in *gen.EmptyReq, out *gen.GenWgKeyPairResponse) error {
	return adaptProtoRPC(out, func() (*gen.GenWgKeyPairResponse, error) { return globalServer.GenWgKeyPair(context.Background(), in) })
}

func (s *protoRPCServer) InstallDashboard(in *gen.InstallDashboardRequest, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) {
		return globalServer.InstallDashboard(context.Background(), in)
	})
}

func (s *protoRPCServer) QueryAutoSelectors(in *gen.EmptyReq, out *gen.QueryAutoSelectorsResponse) error {
	return adaptProtoRPC(out, func() (*gen.QueryAutoSelectorsResponse, error) {
		return globalServer.QueryAutoSelectors(context.Background(), in)
	})
}

func (s *protoRPCServer) AutoSelectorAction(in *gen.AutoSelectorActionRequest, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) { return globalServer.AutoSelectorAction(context.Background(), in) })
}

func (s *protoRPCServer) QueryVPNStatus(in *gen.VPNStatusRequest, out *gen.VPNStatusResponse) error {
	return adaptProtoRPC(out, func() (*gen.VPNStatusResponse, error) {
		return globalServer.QueryVPNStatus(context.Background(), in)
	})
}

func (s *protoRPCServer) SubmitVPNChallenge(in *gen.SubmitVPNChallengeRequest, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) {
		return globalServer.SubmitVPNChallenge(context.Background(), in)
	})
}

func (s *protoRPCServer) CancelVPNChallenge(in *gen.SubmitVPNChallengeRequest, out *gen.ErrorResp) error {
	return adaptProtoRPC(out, func() (*gen.ErrorResp, error) {
		return globalServer.CancelVPNChallenge(context.Background(), in)
	})
}

var _ gen.LibcoreService = (*protoRPCServer)(nil)
